name: SimpleHomes
version: ${project.version}
main: dev.majek.simplehomes.SimpleHomes
api-version: 1.13
authors: [ Majekdor ]
description: Base homes plugin with all the essential features.
website: https://majek.dev
commands:
  simplehomes:
    description: SimpleHomes' main (help) command.
    aliases: [sh]
  home:
    description: Go to a home.
    aliases: [h]
  sethome:
    description: Sets a home at your current location.
    aliases: [newhome]
  delhome:
    description: Deletes one of your homes.
    aliases: [removehome]
  homes:
    description: List all of your homes.
permissions:
  simplehomes.sethome:
    description: Allows players to set a home.
    default: true
  simplehomes.home:
    description: Allows players to go to a home.
    default: true
  simplehomes.homes:
    description: Allows players to view a list of their homes
    default: true
  simplehomes.delhome:
    description: Allows players to delete a home.
    default: true
  simplehomes.nether:
    description: Allows players to sethomes in the nether dimension.
    default: true
  simplehomes.end:
    description: Allows players to set homes in the end dimension.
    default: true
  simplehomes.sethome.max:
    description: Here for tab completion with LuckPerms. Append . and an integer to set max homes.
  simplehomes.delhome.other:
    description: Allows players to delete another player's home.
    default: op
  simplehomes.home.other:
    description: Allows players to travel to another player's home.
    default: op
  simplehomes.homes.other:
    description: Allows players to view other player's homes.
    default: op
  simplehomes.reload:
    description: Allows players to reload the plugin.
    default: op
  simplehomes.sethome.unlimited:
    description: Allows players to set unlimited homes.
    default: op
  simplehomes.delay.bypass:
    description: Allows players to bypass the teleport delay.
    default: op